# apache-otr.conf  (App role Apache virtual host)  -  ns87 (Noaman Shahid), Person B
# Part of bulk release rel-2026-07-27-01. No secrets.

<VirtualHost *:80>
    ServerName ontheradar.local
    DocumentRoot /var/www/html

    <Directory /var/www/html>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog  ${APACHE_LOG_DIR}/otr_error.log
    CustomLog ${APACHE_LOG_DIR}/otr_access.log combined
</VirtualHost>
